#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libmodplug
Version  : 0.8.9.0
Release  : 2
URL      : https://sourceforge.net/projects/modplug-xmms/files/libmodplug/0.8.9.0/libmodplug-0.8.9.0.tar.gz
Source0  : https://sourceforge.net/projects/modplug-xmms/files/libmodplug/0.8.9.0/libmodplug-0.8.9.0.tar.gz
Summary  : The ModPlug mod file playing library.
Group    : Development/Tools
License  : Public-Domain
Requires: libmodplug-lib = %{version}-%{release}
Patch1: 0001-Fix-include-path.patch

%description
libmodplug - the library which was part of the Modplug-xmms project
Web page: http://modplug-xmms.sf.net/

%package dev
Summary: dev components for the libmodplug package.
Group: Development
Requires: libmodplug-lib = %{version}-%{release}
Provides: libmodplug-devel = %{version}-%{release}
Requires: libmodplug = %{version}-%{release}

%description dev
dev components for the libmodplug package.


%package lib
Summary: lib components for the libmodplug package.
Group: Libraries

%description lib
lib components for the libmodplug package.


%prep
%setup -q -n libmodplug-0.8.9.0
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1567187428
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1567187428
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/libmodplug/it_defs.h
/usr/include/libmodplug/modplug.h
/usr/include/libmodplug/sndfile.h
/usr/include/libmodplug/stdafx.h
/usr/lib64/libmodplug.so
/usr/lib64/pkgconfig/libmodplug.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libmodplug.so.1
/usr/lib64/libmodplug.so.1.0.0
